TITLE = "RefugEASE"
SCREEN_WIDTH = 1600
SCREEN_HEIGHT = 950
SIZE = f"{SCREEN_WIDTH}x{SCREEN_HEIGHT}"

# DATABASE CONFIG
DATABASE_NAME = 'db'

# COLORS
LIGHTGREY = '#969393'

# USER STATUS
ACTIVE = 'Active'
INACTIVE = 'Deactivated'