from .login import LoginView
from .plan_detail import PlanDetailView
from .all_plans import AllPlansView
from .add_edit_plan import AddEditPlanView
from .all_volunteers_list import AllVolunteersView
from .messages import MessagesView
from .my_camp_view import MyCampView
from .profile_view import ProfileView
from .new_msg import NewMessageView