from .login import LoginView
from .plan_detail import PlanDetailView
from .all_plans import AllPlansView
from .add_edit_plan import AddEditPlanView
from .all_volunteers_list import AllVolunteersView
from .messages import MessagesView
from .profile_view import ProfileView
from .new_msg import NewMessageView
from .add_edit_camp import AddEditCampView
from .camp_detail import CampDetailView
from .edit_resources import EditResourcesView
from .add_edit_refugee import AddEditRefugeeView
from .departed_refugees import DepartedRefugeesView
from .refugee_profile_view import RefugeeProfileView
from .add_edit_volunteer import AddEditVolunteerView
