# main site metadata and titles
site_name: CareCompear 🍐
site_description: CareCompear 🍐
site_author: Dr Anchit Chandran
site_url: https://anchit-chandran.github.io/foundry/

# copyright information which is shown in the footer
copyright: Copyright &copy; 2023 CareCompear 🍐.

# these lines configure the 'GitHub repo' widget on the top right
repo_url: https://github.com/anchit-chandran/foundry
repo_name: anchit-chandran/foundry

# `mkdocs serve` serves the documentation at custom port
# dev_addr: "127.0.0.1"

nav:
  - "index.md"
  - About:
      - "about.md"
  - "team.md"

theme:
  name: material
  custom_dir: overrides
  logo: _assets/_images/logo.svg
  favicon: _assets/_images/logo.svg
  features:
    - navigation.expand
    - header.autohide
    - navigation.footer # explicitly adds footer prev/next (Material4MkDocs9.0)
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    # - toc.integrate
    - toc.follow

  palette:
    scheme: dark
  font:
    text: Montserrat
    code: Roboto Mono

watch:
  - overrides

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra_css:
  - _assets/_stylesheets/extra.css

# footer links and variables
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/
